name: Update Submodule
on:
  repository_dispatch:
    types:
      - update-submodule
  workflow_dispatch:
jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Authorize Git
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
      - name: Update submodule
        run: |
          git submodule update  --init --recursive --remote -f
      - name: Commit changes
        run: |
          git add writings
          git commit -m "Update submodule to latest commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}